apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-chatbot.fullname" . }}
  labels:
    app: {{ include "rag-chatbot.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "rag-chatbot.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
